<a href="https://colab.research.google.com/github/coleee04/ADS2002-Melanoma-Group-1/blob/main/ADS2002_Melanoma_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing the [Kaggle API](https://github.com/Kaggle/kaggle-api) in Colab

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

# Authenticating with Kaggle using kaggle.json

Navigate to https://www.kaggle.com. Then go to the [Account tab of your user profile](https://www.kaggle.com/me/account) and select Create API Token. This will trigger the download of kaggle.json, a file containing your API credentials.

Then run the cell below to upload kaggle.json to your Colab runtime.

In [14]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# Then move kaggle.json into the folder where the API expects to find it.
!mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json
User uploaded file "kaggle.json" with length 68 bytes

# Using the Kaggle API

For a more complete list of what you can do with the API, visit https://github.com/Kaggle/kaggle-api.

## Listing competitions

In [15]:
!kaggle competitions list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                                           deadline             category         reward  teamCount  userHasEntered
----------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge   2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                            2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                    2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection          2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                  2026-11-02 23:59:00  Featured    850,000 Usd       2020           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                  2026-11-02 23:59:00  Featured    700,000 Usd       1346           False
https://www.kaggle.com/competitions/gemini-3                                  2025-12-12 23:59:00  Featured    500,000 Usd       4086           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming            2025-08-26 23:59:00  Featured    500,000 Usd        601           False
https://www.kaggle.com/competitions/openai-to-z-challenge                     2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                2026-11-09 23:59:00  Featured    450,000 Usd        115           False
https://www.kaggle.com/competitions/pokemon-tcg-ai-battle-challenge-strategy  2026-09-13 23:59:00  Featured    240,000 Usd        288           False
https://www.kaggle.com/competitions/llm-prompt-recovery                       2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection      2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                        2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl           2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                    2026-05-18 23:59:00  Featured    200,000 Usd       1609           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                      2026-04-16 23:59:00  Featured    200,000 Usd       1063           False
https://www.kaggle.com/competitions/datasciencebowl                           2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                    2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                       2022-03-15 23:59:00  Featured    160,000 Usd       2058           False

## Downloading a dataset

In [16]:
!kaggle competitions download \-c siim-isic-melanoma-classification

Downloading siim-isic-melanoma-classification.zip to /content
 11% 11.6G/106G [02:15<18:20, 91.9MB/s]
User cancelled operation

In [ ]:
!unzip data-science-for-good.zip

In [ ]:
import pandas as pd

basepath = "Dept_23-00089/23-00089_ACS_data/23-00089_ACS_race-sex-age/"
rca_df = pd.read_csv(basepath + "ACS_15_5YR_DP05_with_ann.csv")
rca_df.head()

,GEO.id,GEO.id2,GEO.display-label,HC01_VC03,HC02_VC03,HC03_VC03,HC04_VC03,HC01_VC04,HC02_VC04,HC03_VC04,...,HC03_VC108,HC04_VC108,HC01_VC109,HC02_VC109,HC03_VC109,HC04_VC109,HC01_VC110,HC02_VC110,HC03_VC110,HC04_VC110
0,Id,Id2,Geography,Estimate; SEX AND AGE - Total population,Margin of Error; SEX AND AGE - Total population,Percent; SEX AND AGE - Total population,Percent Margin of Error; SEX AND AGE - Total p...,Estimate; SEX AND AGE - Total population - Male,Margin of Error; SEX AND AGE - Total populatio...,Percent; SEX AND AGE - Total population - Male,...,"Percent; CITIZEN, VOTING AGE POPULATION - Citi...","Percent Margin of Error; CITIZEN, VOTING AGE P...","Estimate; CITIZEN, VOTING AGE POPULATION - Cit...","Margin of Error; CITIZEN, VOTING AGE POPULATIO...","Percent; CITIZEN, VOTING AGE POPULATION - Citi...","Percent Margin of Error; CITIZEN, VOTING AGE P...","Estimate; CITIZEN, VOTING AGE POPULATION - Cit...","Margin of Error; CITIZEN, VOTING AGE POPULATIO...","Percent; CITIZEN, VOTING AGE POPULATION - Citi...","Percent Margin of Error; CITIZEN, VOTING AGE P..."
1,1400000US18097310103,18097310103,"Census Tract 3101.03, Marion County, Indiana",6700,435,6700,(X),3167,419,47.3,...,4881,(X),2167,208,44.4,3.3,2714,234,55.6,3.3
2,1400000US18097310104,18097310104,"Census Tract 3101.04, Marion County, Indiana",3309,283,3309,(X),1374,217,41.5,...,2988,(X),1179,194,39.5,6.2,1809,244,60.5,6.2
3,1400000US18097310105,18097310105,"Census Tract 3101.05, Marion County, Indiana",3612,272,3612,(X),1886,186,52.2,...,2546,(X),1280,113,50.3,4.3,1266,158,49.7,4.3
4,1400000US18097310106,18097310106,"Census Tract 3101.06, Marion County, Indiana",3871,489,3871,(X),1802,327,46.6,...,3078,(X),1267,234,41.2,5.6,1811,262,58.8,5.6

In [ ]:
a_df = pd.read_csv(basepath + "ACS_15_5YR_DP05_metadata.csv")
a_df.head()

              GEO.id                                               Id
0            GEO.id2                                              Id2
1  GEO.display-label                                        Geography
2          HC01_VC03         Estimate; SEX AND AGE - Total population
3          HC02_VC03  Margin of Error; SEX AND AGE - Total population
4          HC03_VC03          Percent; SEX AND AGE - Total population

## Uploading a Colab notebook to Kaggle Kernels

Bear with us, as this is a little round-about...

### Downloading a notebook from Colab

To download from Colab, use **File** | **Download .ipynb**

### Then upload the notebook to your Colab runtime

In [ ]:
uploaded = files.upload()
notebook_path = list(uploaded.keys())[0]

In [ ]:
!mkdir -p export
!mv $notebook_path export/
!kaggle kernels init -p export

In [ ]:
import re
your_kaggle_username = 'Your kaggle username'
notebook_title = 'New Kernel'
new_kernel_slug = re.sub(r'[^a-z0-9]+', '-', notebook_title.lower())

In [ ]:
# Documented here: https://github.com/Kaggle/kaggle-api/wiki/Kernel-Metadata
metadata = '''
{
  "id": "%s/%s",
  "title": "%s",
  "code_file": "%s",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": "true",
  "enable_gpu": "false",
  "enable_internet": "true",
  "dataset_sources": [],
  "competition_sources": [],
  "kernel_sources": []
}
''' % (your_kaggle_username, new_kernel_slug, notebook_title, notebook_path)

In [ ]:
!echo '$metadata' > export/kernel-metadata.json
!cat export/kernel-metadata.json

In [ ]:
!kaggle kernels push -p export